### ISSUE TITLE
Usage misunderstanding

### ISSUE THREAD

**Issue by hizliemre** [twino-framework/twino-mq#101]
Hi again,

It seems you are working on sample projects.
There is no **Acknowledge** attribute on **ModelA** class in producer project.
I reproduced and got same problem. Then I added **[Acknowledge(QueueAckDecision.JustRequest)]** to **ModelA** class in **producer** project, the problem is fixed.

The problem is here, persistent delivery handler removes messages from disk after acknowledge is received. But queue is not tracking acknowledge messages because it's disabled by default. Your acknowledge message isn't being tracked and persistent delivery handler's delete message operation isn't triggered.

Yes, there is a usage bug here that causes a misunderstanding. Persistent delivery handler initialization should throw an exception if it's delete operation is triggered by acknowledge and queue's acknowledge option is disabled.

Now, you can fix your problem by adding the attribute and you can be sure, in minor next version (in a few days), an exception will be added to persistent delivery handler initialization to warn. You will not able to start the server with incorrect options.

Thanks for your information about the issue.

_Originally posted by @mhelvacikoylu in https://github.com/twino-framework/twino-mq/issue_comments/711968612_

**Comment by mhelvacikoylu** [comment]
fixed on 4.0.6
